web/dashboard/urls.py
from django.conf.urls import patterns, url

from views import job_status, dropbox_webhook, Frontpage, \
    WebsiteCreate, WebsiteDetail, WebsiteUpdate, WebsiteDelete, WebsiteList, \
    WebsiteSync, WebsitePreview, WebsitePublish, WebsiteStencil, WebsiteEditFile



urlpatterns = patterns('',
    url(r'^webhook$', dropbox_webhook),
    url(r'^$', Frontpage.as_view(), name='frontpage'),
    url(r'^site$', WebsiteList.as_view(), name='site_list'),
    url(r'^job/(?P<queue>\w+)', job_status, name='job_status'),
    url(r'^site/add/$', WebsiteCreate.as_view(), name='site_create'),
    url(r'^site/(?P<pk>\w+)/$', WebsiteDetail.as_view(), name='site_detail'),
    url(r'^site/(?P<pk>\w+)/delete$', WebsiteDelete.as_view(), name='site_delete'),
    url(r'^site/(?P<pk>\w+)/update$', WebsiteUpdate.as_view(), name='site_update'),
    url(r'^site/(?P<pk>\w+)/sync', WebsiteSync.as_view(), name='site_sync'),
    url(r'^site/(?P<pk>\w+)/preview$', WebsitePreview.as_view(), name='site_preview'),
    url(r'^site/(?P<pk>\w+)/publish', WebsitePublish.as_view(), name='site_publish'),
    url(r'^site/(?P<pk>\w+)/files/(?P<path>.*)$', WebsiteEditFile.as_view(), name='site_file_editor'),
    url(r'^site/(?P<pk>\w+)/stencil$', WebsiteStencil.as_view(), name='site_stencil'),
)

web/web/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings

urlpatterns = patterns('',
                       url(r'^', include('dashboard.urls')),
                       url(r'^accounts/', include('allauth.urls')),
                       url(r'^admin/', include(admin.site.urls))
                       )

urlpatterns += patterns('',
                        (r'^rq/', include('django_rq.urls')),
                        )
if settings.DEBUG:
    from django.conf.urls.static import static

    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT, show_indexes=True)
    # urlpatterns += url(r'^__debug__/', include(debug_toolbar.urls)),

web/dashboard/models.py
from allauth.socialaccount.models import SocialApp
from django.db import models
from django.core.urlresolvers import reverse
import requests
from requests_oauthlib import OAuth1
from remotes import DropboxRemote, FileSystemRemote
import os.path
from django.conf import settings


class Remotes:
    Dropbox = 'dropbox'  # same as allauth provider name
    FileSystem = 'fs'


REMOTE_CHOICES = (
    (Remotes.Dropbox, 'Dropbox'),
    (Remotes.FileSystem, 'Local File System'),
)


def get_dropbox_key(app_key, app_secret, token, token_secret):
    auth = OAuth1(app_key, app_secret, token, token_secret)
    resp = requests.post('https://api.dropbox.com/1/oauth2/token_from_oauth1', auth=auth)
    return resp.json()['access_token']


class SyncCursor(models.Model):
    cursor = models.CharField(max_length=255)
    hash = models.CharField(max_length=255)
    created = models.DateTimeField(auto_now_add=True)
    website = models.ForeignKey('WebSite')


class WebSite(models.Model):
    user = models.ForeignKey('auth.User')
    domain = models.CharField(max_length=255)
    remote = models.CharField(choices=REMOTE_CHOICES, max_length=255)

    def get_absolute_url(self):
        return reverse('site_detail', args=[self.pk])

    def get_remote_instance(self):
        if self.remote == Remotes.Dropbox:
            social = self.user.socialaccount_set.filter(provider=self.remote).first()
            if social and 'oauth2key' in social.extra_data:
                return DropboxRemote(social.extra_data['oauth2key'], '/' + self.get_unique_id())
        if self.remote == Remotes.FileSystem:
            return FileSystemRemote(os.path.join(settings.USER_SITES_STORAGE, str(self.user.pk), str(self.pk)))

    def _dropbox_create_hook(self):
        """Cache OAuth2 key in extra data"""
        social = self.user.socialaccount_set.filter(
            provider=Remotes.Dropbox).first()
        if social and 'oauth2key' not in social.extra_data:
            token = social.socialtoken_set.first()
            provider = SocialApp.objects.get(provider=Remotes.Dropbox)
            key = get_dropbox_key(provider.client_id, provider.secret, token.token, token.token_secret)
            social.extra_data['oauth2key'] = key
            social.save()

    def _fs_create_hook(self):
        remote = self.get_remote_instance()
        remote.initialize()

    def initialize_remote(self):
        if self.remote == Remotes.Dropbox:
            self._dropbox_create_hook()
        if self.remote == Remotes.FileSystem:
            self._fs_create_hook()

    def __unicode__(self):
        return self.domain

    def get_unique_id(self):
        return "%s%d" % (self.domain.replace(".", ""), self.pk)

web/dashboard/forms.py
# -*- coding: utf8 -*-
from django import forms
from django.conf import settings
import os.path


class StencilForm(forms.Form):

    @staticmethod
    def get_stencil_choices():
        for folder in os.listdir(settings.STENCIL_PATH):
            if os.path.isdir(os.path.join(settings.STENCIL_PATH, folder)):
                yield (folder, folder)

    def __init__(self, *args, **kwds):
        super(StencilForm, self).__init__(*args, **kwds)
        self.fields['stencil'] = forms.ChoiceField(label='Stencil', choices=StencilForm.get_stencil_choices())

web/dashboard/views.py
import json
from django.contrib.auth.decorators import login_required
from django.views.generic.detail import SingleObjectMixin
import django_rq
from os.path import join

from django.http import HttpResponse, JsonResponse, HttpResponseBadRequest, HttpResponseRedirect, HttpResponseNotAllowed
from django.shortcuts import get_object_or_404, render, redirect
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import ListView, CreateView, UpdateView, DeleteView, DetailView, View, FormView, TemplateView
from django.core.urlresolvers import reverse_lazy
from django.conf import settings
from dropbox.rest import ErrorResponse

from forms import StencilForm
from models import WebSite
from tasks import sync_site, preview_site, publish_site, copy_stencil


class WebsiteAuthMixin(SingleObjectMixin):

    @classmethod
    def as_view(cls):
        return login_required(super(WebsiteAuthMixin, cls).as_view())

    def get_queryset(self):
        if self.request.user.is_anonymous():
            return WebSite.objects.none()
        else:
            return WebSite.objects.filter(user=self.request.user.pk)


class WebsiteCommand(WebsiteAuthMixin, View):

    def post(self, request, *args, **kwargs):
        job = self.get_job()
        return HttpResponseRedirect(reverse_lazy('job_status', args=['default']) + '?task_id=' + job.id)

    def get_job(self, *args):
        raise NotImplemented


class Frontpage(TemplateView):
    template_name = 'dashboard/frontpage.html'

    def get(self, request, *args, **kwargs):
        if not request.user.is_anonymous() and request.user.website_set.exists():
            return redirect('site_list')
        return super(Frontpage, self).get(request, *args, **kwargs)


class WebsiteList(ListView):
    model = WebSite

    def get_queryset(self):
        qs = super(WebsiteList, self).get_queryset()
        if self.request.user.is_anonymous():
            return qs.none()
        else:
            return qs.filter(user=self.request.user.pk)


class WebsiteCreate(CreateView):
    model = WebSite
    fields = ['domain', 'remote']

    def get_form(self, form_class):
        form = super(WebsiteCreate, self).get_form(form_class)
        form.instance.user = self.request.user
        return form

    def form_valid(self, form):
        response = super(WebsiteCreate, self).form_valid(form)
        form.instance.initialize_remote()
        return response


class WebsiteDetail(WebsiteAuthMixin, DetailView):
    model = WebSite

    def get_context_data(self, **kwargs):
        data = super(WebsiteDetail, self).get_context_data(**kwargs)
        remote = self.object.get_remote_instance()
        # check if folder exists
        try:
            remote.list().next()
        except (ErrorResponse, StopIteration) as e:
            data['empty'] = True
            data['form'] = StencilForm()
        # TODO: move to async code (AJAX handler)
        data['files'] = remote.list()
        return data


class WebsiteUpdate(WebsiteAuthMixin, UpdateView):
    model = WebSite


class WebsiteDelete(WebsiteAuthMixin, DeleteView):
    model = WebSite
    success_url = reverse_lazy('frontpage')

    def post(self, request, *args, **kwargs):
        return self.delete(request, *args, **kwargs)


class WebsiteSync(WebsiteCommand):
    def get_job(self):
        site = self.get_object()
        return sync_site.delay(site.pk)


class WebsitePreview(WebsiteCommand):
    def get_job(self):
        site = self.get_object()
        return preview_site.delay(site.pk)


class WebsitePublish(WebsiteCommand):
    def get_job(self):
        site = self.get_object()
        return publish_site.delay(site.pk)


class WebsiteEditFile(WebsiteAuthMixin, View):
    # TODO: to FormView

    def get(self, request, path, *args, **kwds):
        website = self.get_object()
        remote = website.get_remote_instance()
        content = remote.read_file(path)
        return render(request, 'dashboard/file_editor.html', {'path': path, 'content': content, 'object': website})

    def post(self, request, path, *args, **kwds):
        website = self.get_object()
        remote = website.get_remote_instance()
        remote.write_file(path, request.POST['content'])
        return redirect('site_detail', website.pk)


class WebsiteStencil(WebsiteAuthMixin, View):
    # TODO: to FormView

    def post(self, request, *args, **kwds):
        website = self.get_object()
        form = StencilForm(request.POST)
        if form.is_valid():
            src = join(settings.STENCIL_PATH, form.cleaned_data['stencil'])
            job = copy_stencil.delay(website.pk, src)
            return HttpResponseRedirect(reverse_lazy('job_status', args=['default']) + '?task_id=' + job.id)
        else:
            return HttpResponseBadRequest('Form not valid: {0}'.format(form.errors))


def job_status(request, queue):
    if 'task_id' in request.GET:
        q = django_rq.get_queue(queue)
        job = q.fetch_job(request.GET['task_id'])
        job_data = job.to_dict()
        del job_data['data']
        job_data['task_id'] = request.GET['task_id']
        job_data['result'] = job.result
        return JsonResponse(job_data)
    else:
        return HttpResponseBadRequest("specify task_id")


@csrf_exempt
def dropbox_webhook(request):
    if request.method == 'GET':
        return HttpResponse(request.GET['challenge'])
    if request.method == 'POST':
        data = json.loads(request.body)
        if 'delta' in data and 'users' in data['delta']:
            for uid in data['delta']['users']:
                pass
        return HttpResponse('OK')

web/dashboard/templates/dashboard/base.html
{% extends 'base.html' %}

web/dashboard/templates/dashboard/file_editor.html
{% extends 'dashboard/base.html' %}

{% block bottomjs %}
  {{ block.super }}
  <script src="http://ajaxorg.github.io/ace-builds/src-noconflict/ace.js"></script>
  <script type="text/javascript">
    $(function () {
      var editor = ace.edit("editor");
      editor.setTheme("ace/theme/monokai");
      editor.getSession().setMode("ace/mode/html");
      editor.on('change', function() {
        $('[name=content]').prop('value', editor.getSession().getDocument().getValue());
      })
    });
  </script>
{% endblock %}

{% block head %}
  {{ block.super }}
  <style type="text/css" media="screen">
    body {
        overflow: hidden;
    }

    [name=content] {
      display: none;
    }

    #editor {
      width: 500px;
      height: 500px;
    }
  </style>
{% endblock %}

{% block content %}
  {{ block.super }}
  <h1>Edit file {{ path }}</h1>
  <form action="{% url 'site_file_editor' object.pk path %}" method="POST">
    <textarea name="content" cols="30" rows="10">{{ content }}</textarea>
    {% csrf_token %}
    <input class="btn btn-primary" type="submit" value="Сохранить"/>
    <div id="editor">{{ content | escape }}</div>
  </form>
{% endblock %}

web/dashboard/templates/dashboard/frontpage.html
{% extends "dashboard/base.html" %}
{% load socialaccount account %}
{% block header %}
  <div class="promo-banner">
    <div class="container-fluid">
      <h1 class="promo-banner__header">CMSLess - это сервис для генерации статических сайтов сделанный
        веб-разработчиками для веб-разработчиков</h1>
    </div>
  </div>
{% endblock %}

{% block content %}
  <div class="frontpage-form z-depth-2">
    <form action="{% url 'site_create' %}" method="post">
      <h2 class="frontpage-form__header">Зарегистрироваться</h2>

      {% if user.is_anonymous %}
      <div class="form-group">
        <a class="btn btn-primary" href="{% provider_login_url "dropbox" %}"><i class="glyphicon glyphicon-link"></i> Дайте доступ к Dropbox</a>
      </div>
      {% else %}
      <div class="form-group">
        <div class="btn btn-primary"><i class="glyphicon glyphicon-link"></i> Вы зашли как {% user_display user %}</div>
        <div class="help-text"><a href="{% url 'account_logout' %}">Сменить пользователя</a></div>
      </div>
      {% endif %}
      <div class="form-group">
        <label for="">Придумайте домен или просто название</label>
        <input type="text" class="form-control" name="domain"/>
      </div>
{#      <strong class="form-group">Выберите начальный шаблон</strong>#}
{#      <div class="radio">#}
{#        <label>#}
{#          <input type="radio" name="template"/>#}
{#          <div class="frontpage-form__screenshot" style="background-image: url('{{ MEDIA_URL }}stencils/default.png')"></div>#}
{#          Шаблон Jekyll по умолчанию#}
{#        </label>#}
{#      </div>#}
      {% if user.is_anonymous %}
        <a class="btn btn-primary frontpage-form__submit" href="{% url 'account_signup' %}">Зарегистрироваться</a>
        <hr/>
        <span>Уже зарегистрированы?</span>
        <a href="{% url 'account_login' %}">Войти</a>
        <span>или</span>
        <a href="{% url 'account_reset_password' %}">Напомнить пароль</a>
      {% else %}
        <input type="hidden" name="remote" value="dropbox"/>
        {% csrf_token %}
        <input type="submit" class="btn btn-primary frontpage-form__submit" value="Создать сайт"/>
      {% endif %}

    </form>
  </div>

  <section class="frontpage-faq">
    <h2>FAQ</h2>
    <span class="frontpage-faq__question">
      Что это такое?
    </span>
    <span class="frontpage-faq__answer">
      CMSLESS - это сплав силы и умения
    </span>

    <span class="frontpage-faq__question">
      Что это такое?
    </span>
    <span class="frontpage-faq__answer">
      CMSLESS - это сплав силы и умения
    </span>
  </section>
{% endblock %}

web/dashboard/templates/dashboard/site_create.html
{% extends 'dashboard/base.html' %}
{% load zenforms %}

{% block content %}
    {{ block.super }}
    <form action="{% url 'site_create' %}" method="post">
        {% zenform form %}
        {% csrf_token %}
        <input type="submit" value="Create"/>
    </form>
    
{% endblock %}

web/dashboard/templates/dashboard/website_confirm_delete.html
{% extends 'dashboard/base.html' %}

{% block content %}
  {{ block.super }}
  <h1>Удалить сайт {{ object.domain }}?</h1>
  <form action="{% url 'site_delete' object.pk %}" method="POST">
    {% csrf_token %}
    <input type="submit" value="Да!"/>
  </form>
{% endblock %}

web/dashboard/templates/dashboard/website_detail.html
{% extends 'dashboard/base.html' %}

{% block bottomjs %}
  {{ block.super }}
  <script type="text/javascript" src="{{ STATIC_URL }}rxjs/dist/rx.all.min.js"></script>
  <script type="text/javascript" src="{{ STATIC_URL }}bootstrap/dist/js/bootstrap.min.js"></script>
  <script type="text/javascript" src="{{ STATIC_URL }}dashboard/scripts/main.js"></script>
{% endblock %}

{% block content %}
  {{ block.super }}
  <h1>{{ object.domain }}</h1>
  <a class="btn btn-default" href="{% url 'site_update' object.pk %}"><i class="glyphicon glyphicon-pencil"></i>
    Изменить</a>
  <form action="{% url 'site_sync' object.pk %}" method="POST" id="target">
    {% csrf_token %}
    <button class="btn btn-default">Обновить</button>
  </form>
  <form action="{% url 'site_preview' object.pk %}" method="POST">
    {% csrf_token %}
    <button class="btn btn-default">Предпросмотр</button>
  </form>
  <form action="{% url 'site_publish' object.pk %}" method="POST">
    {% csrf_token %}
    <button class="btn btn-primary">Публикация</button>
  </form>
  <br/>

  {% if empty %}
    Website does not exist. You can initialize it with stencil:
    <form action="{% url 'site_stencil' object.pk %}" method="post">
      {{ form.as_p }}
      {% csrf_token %}
      <input class="btn btn-primary" type="submit"/>
    </form>
  {% else %}
    Remote: {{ object.get_remote_display }}
    <ul class="pills pills-stacked">
      {% for file in files %}
        <li><a href="{% url 'site_file_editor' object.pk file.path %}">{{ file }}</a></li>
      {% endfor %}
    </ul>
  {% endif %}
{% endblock %}

web/dashboard/templates/dashboard/website_form.html
{% extends 'dashboard/base.html' %}
{% load zenforms %}

{% block head %}
  {{ block.super }}
{% endblock %}

{% block content %}
    {{ block.super }}
    <form class="form" action="{% if form.instance.pk %}{% url 'site_update' form.instance.pk %}{% else %}{% url 'site_create' %}{% endif %}" method="POST">
        {% izenform form options notag=1 %}
        {% csrf_token %}
        <input type="submit"/>
    </form>
{% endblock %}

web/dashboard/templates/dashboard/website_list.html
{% extends 'base.html' %}
{% load account socialaccount %}

{% block bottomjs %}
  {{ block.super }}
  {% providers_media_js %}
{% endblock %}

{% block content %}
  {% if not user.is_anonymous %}
    <h3>Ваши сайты:</h3>
    <table class="table">
      {% for site in object_list %}
        <tr>
          <td><a href="{% url 'site_detail' site.id %}">{{ site }}</a></td>
          <td><a class="btn btn-default" href="{% url 'site_delete' site.id %}">Удалить</a></td>
        </tr>
      {% empty %}
        Пока у вас нет сайтов
      {% endfor %}
    </table>
    <a class="btn btn-primary" href="{% url 'site_create' %}">Добавить сайт</a>
  {% endif %}
{% endblock %}